# Generated by Django 4.2 on 2023-04-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
