# Generated by Django 4.1.7 on 2023-04-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.TextField()),
                ('sphone', models.TextField()),
                ('price', models.TextField()),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
