# Generated by Django 4.1.7 on 2023-04-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pname',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='product',
            name='sphone',
            field=models.CharField(max_length=122),
        ),
    ]
