# Generated by Django 4.1.7 on 2023-04-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0004_alter_product_image_alter_product_pname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=122)),
                ('wimage', models.ImageField(upload_to='workshop/')),
                ('wabout', models.CharField(max_length=122)),
                ('wrange', models.CharField(max_length=122)),
                ('wcity', models.CharField(max_length=122)),
                ('wdatetime', models.CharField(max_length=122)),
            ],
        ),
    ]
