# Generated by Django 4.1.7 on 2023-04-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0005_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='wrange',
            field=models.CharField(default='', max_length=122),
        ),
    ]
