# Generated by Django 4.1.7 on 2023-04-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0006_alter_workshop_wrange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='wrange',
            field=models.CharField(blank=True, default='', max_length=122, null=True),
        ),
    ]
