# Generated by Django 4.1.7 on 2023-04-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0007_alter_workshop_wrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='wid',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
