# Generated by Django 4.1.7 on 2023-04-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0008_workshop_wid'),
    ]

    operations = [
        migrations.CreateModel(
            name='workshopbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=122)),
                ('wid', models.CharField(max_length=122)),
                ('pid', models.CharField(max_length=122)),
            ],
        ),
    ]
