# Generated by Django 4.1.7 on 2023-04-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0009_workshopbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=122)),
                ('buyerid', models.CharField(max_length=122)),
                ('sellerid', models.CharField(max_length=122)),
                ('product_name', models.CharField(max_length=122)),
                ('order_date', models.DateField(max_length=122)),
            ],
        ),
    ]
