# Generated by Django 4.1.7 on 2023-04-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0012_product_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
